### ISSUE TITLE
Problems on osx-64

### ISSUE THREAD

**Issue by blackbox-tech** [conda-forge/awscli-feedstock#717] opened 2021-01-11 12:24 UTC
Not sure sure if you can help, but I raised [an issue on conda-forge](https://github.com/conda-forge/conda-forge.github.io/issues/1239) as this receipe does not seem to currently work on osx-64

**Comment by tkelman** [comment] 2021-01-11 21:11
duplicate of #718

**Closed by tkelman** 2021-01-11 21:11 UTC
